### ISSUE TITLE
FR: config option to reduce verbosity

### ISSUE THREAD

**Issue by zxyz** [metal-stack/nftables-exporter#15]
Hello, 

thanks for nftables-exporter, very much appreciated!
Two minor wishes from my side:

A config option to be able to not log scraping would be great. Syslog is full of:

```
Apr  7 10:00:43 <hostname> nftables_exporter[3862407]: 2023/04/07 10:00:43 collecting nftables counters...
Apr  7 10:00:43 <hostname> nftables_exporter[3862407]: 2023/04/07 10:00:43 collecting metrics
Apr  7 10:01:43 <hostname> nftables_exporter[3862407]: 2023/04/07 10:01:43 collecting nftables counters...
Apr  7 10:01:43 <hostname> nftables_exporter[3862407]: 2023/04/07 10:01:43 collecting metrics
Apr  7 10:02:43 <hostname> nftables_exporter[3862407]: 2023/04/07 10:02:43 collecting nftables counters...
Apr  7 10:02:43 <hostname> nftables_exporter[3862407]: 2023/04/07 10:02:43 collecting metrics
```
which is useful in case of debugging but generally imho not needed. It seems like a minor detail, but having two log lines every scrape on every instance it's running on  accumulates over the months.

The second wish would be a config option to not have go and process metrics in the scrape, e. g.:

```
go_gc_duration_seconds{quantile="0"} 4.6041e-05
go_gc_duration_seconds{quantile="0.25"} 8.8713e-05
go_gc_duration_seconds{quantile="0.5"} 0.00010367
go_gc_duration_seconds{quantile="0.75"} 0.000171977
go_gc_duration_seconds{quantile="1"} 0.001604148
go_gc_duration_seconds_sum 0.009132447
go_gc_duration_seconds_count 46
go_goroutines 7
go_info{version="go1.20.1"} 1
go_memstats_alloc_bytes 1.81448e+06
go_memstats_alloc_bytes_total 5.3474688e+07``
[...]
process_cpu_seconds_total 0.88
process_max_fds 1024
process_open_fds 17
process_resident_memory_bytes 1.6273408e+07
process_start_time_seconds 1.68084923942e+09
process_virtual_memory_bytes 7.3631744e+08
process_virtual_memory_max_bytes 1.8446744073709552e+19
```

The reasoning is the same as above: needed in case of debugging but imho unneeded resources in normal operations. 

Thanks for considering!

**Comment by majst01** [comment]
Hi @zxyz as this is an open source project, we encourage all users to contribute. I promise we will review any valuable PR. So feel free to open such.

**Comment by zxyz** [comment]
Hey @majst01, sorry, but I have absolutely no knowledge of go, otherwise I'd do so.

**Comment by majst01** [comment]
Closing this, feel free to reopen at wish
